GET http://127.0.0.1:8000/api/posts

###

POST http://127.0.0.1:8000/api/posts
Content-Type: application/json

{
    "title": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    "img": "https://images.pexels.com/photos/2078126/pexels-photo-2078126.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
}

###

DELETE http://127.0.0.1:8000/api/posts/5


###

PUT http://127.0.0.1:8000/api/posts/3

Content-Type: application/json

{
    "title": "not Third Post - updated",
    "content": "This is my third post",
    "img": "https://images.pexels.com/photos/3199036/pexels-photo-3199036.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
}



###
GET http://127.0.0.1:8000/api/comments

###

POST http://127.0.0.1:8000/api/comments
Content-Type: application/json

{
    "comment-id": 1,
    "content": "Second comment from laravel"
}

